manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      
    - name: sayu-hub
      url-base: https://github.com/sayu-hub

    - name: badjeff    # <-- PMW3610
      url-base: https://github.com/badjeff

    # - name: sekigon-gonnoc  # <-- PAW3222
    #   url-base: https://github.com/sekigon-gonnoc

    - name: caksoylar  # <-- RGB LED
      url-base: https://github.com/caksoylar

    - name: zettaface  # <-- Input Processor Keybind
      url-base: https://github.com/zettaface

    # - name: te9no  # <-- Input Processor Keybind
    #   url-base: https://github.com/te9no

    - name: kot149
      url-base: https://github.com/kot149

    - name: 4mplelab
      url-base: https://github.com/4mplelab

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: zmk-0.4

    # - name: zmk-driver-paw3222
    #   remote: sekigon-gonnoc
    #   revision: main

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main

    - name: zmk-layout-shift
      remote: kot149
      revision: v1

    - name: zmk-scroll-snap
      remote: kot149
      revision: v1

    - name: zmk-feature-charge-indicator
      remote: 4mplelab
      revision: main

  self:
    path: config
